### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by bvarner** [reiver/go-v4l2#1]
Perhaps you can help me out here...

I've managed to read capabilities.
I've managed to set a pixelformat.

I haven't been able to figure out how to set the buffer request data, or turn on streaming.

Any advice?

**Comment by reiver** [comment]
Hey Bryan,

I haven't finished this library yet.

(There is still a lot of work left to do on it.)

It is not yet ready for general usage yet.

Which is why there is a lack of comprehensive documentation and tutorials.

-- Charles

**Comment by bvarner** [comment]
Well that certainly explains why I was having issues figuring it out!

Thanks for the response, and best of luck.
